name: update

on:
  schedule:
    # at 12:05 on Wednesday, JST
    - cron: '5 3 * * 3'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: >
          curl -fsSL https://api.github.com/repos/vim/vim/tags |
          jq -r '.[0].name' |
          sed -e 's/^v//' |
          tee latest.txt
      - run: echo "value=$(cat latest.txt)" >> "$GITHUB_OUTPUT"
        id: version
      - run: sed -i.bak 's/vim_version := .*/vim_version := ${{ steps.version.outputs.value }}/' Makefile
      - run: rm -f latest.txt Makefile.bak
      - run: |
          if git diff --exit-code --quiet
          then
            echo 'changed=false' >> "$GITHUB_OUTPUT"
          else
            echo 'changed=true' >> "$GITHUB_OUTPUT"
          fi
        id: diff
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '<41898282+github-actions[bot]@users.noreply.github.com>'
        if: steps.diff.outputs.changed
      - run: |
          git checkout -b 'update-to-${{ steps.version.outputs.value }}'
          git add .
          git commit -m 'update vim version' --allow-empty
        if: steps.diff.outputs.changed
      - run: git push origin 'update-to-${{ steps.version.outputs.value }}'
        if: steps.diff.outputs.changed
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            await github.request(`POST /repos/${owner}/${repo}/pulls`, {
              owner,
              repo,
              head: 'update-to-${{ steps.version.outputs.value }}',
              base: 'master',
              title: 'update vim version',
              body: '',
            });
        if: steps.diff.outputs.changed
